class ArtikelIslami {
  String title, author, date, image, description;

  ArtikelIslami(
      {required this.title,
      required this.author,
      required this.date,
      required this.image,
      required this.description});
}

var dataArtikelIslam = [
  ArtikelIslami(
    title: 'Fatwa Ulama: Puasa Rajab',
    author: 'Yulian Purnama, S.Kom',
    date: '2 Mei 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2014/05/02-Fatwa-Ulama-Puasa-Rajab-810x500.png',
    description: '  Fatwa Al Lajnah Ad Daimah Lil Buhuts Wal Ifta’ '
        '\nSoal: Puasa sunnah Rajab itu dianjurkan pada awal bulan, tengahnya atau akhirnya? '
        '\nJawab: Tidak ada hadits yang shahih yang khusus menyatakan adanya keutamaan puasa bulan Rajab selain hadits yang dikeluarkan oleh An Nasa-i dan Abu Daud, yang dishahihkan oleh Ibnu Khuzaimah, dari hadits Usamah, ia berkata: '
        '\n ذلك شهر يغفل عنه الناس بين رجب ورمضان ، وهو شهر ترفع فيه الأعمال إلى رب العالمين فأحب أن يرفع عملي وأنا صائم  يا رسول الله ، لم أرك تصوم من شهر من الشهور ما تصوم من شعبان ، قال :قلت : '
        '\n“aku bertanya: wahai Rasulullah, belum pernah aku melihatmu puasa di bulan lain sebagaimana puasamu pada bulan Sya’ban.'
        '\nBeliau bersabda: "Itu adalah bulan yang banyak dilalaikan manusia antara Rajab dan Ramadhan". Dan bulan itu adalah bulan yang di dalamnya diangkat amalan-amalan kepada Rabbul ‘Alamin. Maka aku suka jika ketika aku sedang berpuasa” '
        '\nTerdapat juga hadits-hadits umum yang menganjurkan mengerjakan puasa tiga hari atau puasa ayyamul bidh setiap bulannya. Yaitu pada tanggal 13, 14, 15 (bulan Hijriah). Dan juga anjuran untuk memperbanyak puasa di bulan-bulan haram, juga puasa senin-kamis. Bulan Rajab termasuk dalam keumuman hadits-hadits tersebut. '
        '\nika anda bersemangat untuk berpuasa pada hari-hari tertentu (di bulan Rajab) maka puasalah pada ayyamul bidh yang tiga hari tadi, atau pada hari senin dan kamis, atau jika bukan (pada hari-hari tersebut pun boleh), perkaranya luas.Adapun mengkhususkan hari tertentu sebagai hari puasa Rajab, kami tidak mengetahui ada dasarnya dari Syariat.Wabillahi at taufiq, washallallahu ‘ala nabiyyina muhammadin wa ‘ala ahlihi washahbihi wasallam.',
  ),
  ArtikelIslami(
      title: 'Berbenah Diri Menyambut Bulan Ramadhan',
      author: 'Abdullah Taslim, Lc, MA.',
      date: '13 Februari 2021',
      image:
          'https://static.muslim.or.id/wp-content/uploads/2010/08/Berbenah-Diri-Menyambut-Bulan-Ramadhan-muslimorid-810x500.jpg',
      description:
          ' Allah Ta’ala telah mengutamakan sebagian waktu (zaman) di atas sebagian lainnya, sebagaimana Dia mengutamakan sebagian manusia di atas sebagian lainnya dan sebagian tempat di atas tempat lainnya.'
          '\nAllah Ta’ala berfirman,وَرَبُّكَ يَخْلُقُ مَا يَشَاءُ وَيَخْتَارُ مَا كَانَ لَهُمُ الْخِيَرَةُ  '
          '\n“Dan Rabbmu menciptakan apa yang Dia kehendaki dan memilihnya, sekali-kali tidak ada pilihan bagi mereka” (QS al-Qashash:68). '
          '\nSyaikh ‘Abdur Rahman as-Sa’di ketika menafsirkan ayat di atas, beliau berkata, “(Ayat ini menjelaskan) menyeluruhnya ciptaan Allah bagi seluruh makhluk-Nya, berlakunya kehendak-Nya bagi semua ciptaan-Nya, dan kemahaesaan-Nya dalam memilih dan mengistimewakan apa (yang dikehendaki-Nya), baik itu manusia, waktu (jaman) maupun tempat”[1]. '
          '\nTermasuk dalam hal ini adalah bulan Ramadhan yang Allah Ta’ala utamakan dan istimewakan dibanding bulan-bulan lainnya, sehingga dipilih-Nya sebagai waktu dilaksanakannya kewajiban berpuasa yang merupakan salah satu rukun Islam.'
          '\nSungguh Allah Ta’ala memuliakan bulan yang penuh berkah ini dan menjadikannya sebagai salah satu musim besar untuk menggapai kemuliaan di akhirat kelak, yang merupakan kesempatan bagi hamba-hamba Allah Ta’ala yang bertakwa untuk berlomba-lomba dalam melaksanakan ketaatan dan mendekatkan diri kepada-Nya[2]. '
          '\nDaftar Isi  sembunyikan : '
          '\n1. Bagaimana Seorang Muslim Menyambut Bulan Ramadhan? '
          '\n2. Meraih Takwa dan Kesucian Jiwa dengan Puasa Ramadhan '
          '\n3. Penutup . Bagaimana Seorang Muslim Menyambut Bulan Ramadhan? '
          '\nBulan Ramadhan yang penuh kemuliaan dan keberkahan, padanya dilipatgandakan amal-amal kebaikan, disyariatkan amal-amal ibadah yang agung, di buka pintu-pintu surga dan di tutup pintu-pintu neraka[3].'
          '\nOleh karena itu, bulan ini merupakan kesempatan berharga yang ditunggu-tunggu oleh orang-orang yang beriman kepada Allah Ta’ala dan ingin meraih ridha-Nya.'
          '\nDan karena agungnya keutamaan bulan suci ini, Rasulullah shallallahu ‘alaihi wa sallam selalu menyampaikan kabar gembira kepada para sahabat radhiyallahu ‘anhum akan kedatangan bulan yang penuh berkah ini[4].'
          '\nSahabat yang mulia, Abu Hurairah radhiyallahu ‘anhu berkata, Rasulullah shallallahu ‘alaihi wa sallam bersabda, menyampaikan kabar gembira kepada para sahabatnya, “Telah datang bulan Ramadhan yang penuh keberkahan, Allah mewajibkan kalian berpuasa padanya, pintu-pintu surga di buka pada bulan itu, pintu-pintu neraka di tutup, dan para setan dibelenggu. Pada bulan itu terdapat malam (kemuliaan/lailatul qadr) yang lebih baik dari seribu bulan, barangsiapa yang terhalangi (untuk mendapatkan) kebaikan malam itu maka sungguh dia telah dihalangi (dari keutamaan yang agung)”[5].'
          '\nImam Ibnu Rajab, ketika mengomentari hadits ini, beliau berkata, “Bagaimana mungkin orang yang beriman tidak gembira dengan dibukanya pintu-pintu surga? Bagaimana mungkin orang yang pernah berbuat dosa (dan ingin bertobat serta kembali kepada Allah Ta’ala) tidak gembira dengan ditutupnya pintu-pintu neraka? Dan bagaimana mungkin orang yang berakal tidak gembira ketika para setan dibelenggu?”[6]. '
          '\nDulunya, para ulama salaf jauh-jauh hari sebelum datangnya bulan Ramadhan berdoa dengan sungguh-sungguh kepada Allah Ta’ala agar mereka mencapai bulan yang mulia ini, karena mencapai bulan ini merupakan nikmat yang besar bagi orang-orang yang dianugerahi taufik oleh Alah Ta’ala. Mu’alla bin al-Fadhl berkata, “Dulunya (para salaf) berdoa kepada Allah Ta’ala (selama) enam bulan agar Allah mempertemukan mereka dengan bulan Ramadhan, kemudian mereka berdoa kepada-Nya (selama) enam bulan (berikutnya) agar Dia menerima (amal-amal shaleh) yang mereka (kerjakan)”[7].'
          '\nMaka hendaknya seorang muslim mengambil teladan dari para ulama salaf dalam menyambut datangnya bulan Ramadhan, dengan bersungguh-sungguh berdoa dan mempersiapkan diri untuk mendulang pahala kebaikan, pengampunan serta keridhaan dari Allah Ta’ala, agar di akhirat kelak mereka akan merasakan kebahagiaan dan kegembiraan besar ketika bertemu Allah Ta’ala dan mendapatkan ganjaran yang sempurna dari amal kebaikan mereka. Rasulullah shallallahu ‘alaihi wa sallam bersabda, “Orang yang berpuasa akan merasakan dua kegembiraan (besar): kegembiraan ketika berbuka puasa dan kegembiraan ketika dia bertemu Allah”[8]. '
          '\nTentu saja persiapan diri yang dimaksud di sini bukanlah dengan memborong berbagai macam makanan dan minuman lezat di pasar untuk persiapan makan sahur dan balas dendam ketika berbuka puasa. Juga bukan dengan mengikuti berbagai program acara Televisi yang lebih banyak merusak dan melalaikan manusia dari mengingat Allah Ta’ala dari pada manfaat yang diharapkan, itupun kalau ada manfaatnya.'
          '\nTapi persiapan yang dimaksud di sini adalah mempersiapkan diri lahir dan batin untuk melaksanakan ibadah puasa dan ibadah-ibadah agung lainnya di bulan Ramadhan dengan sebaik-sebaiknya, yaitu dengan hati yang ikhlas dan praktek ibadah yang sesuai dengan petunjuk dan sunnah Rasulullah shallallahu ‘alaihi wa sallam. Karena balasan kebaikan/keutamaan dari semua amal shaleh yang dikerjakan manusia, sempurna atau tidaknya, tergantung dari sempurna atau kurangnya keikhlasannya dan jauh atau dekatnya praktek amal tersebut dari petunjuk Nabi shallallahu ‘alaihi wa sallam[9].'
          '\nHal ini diisyaratkan dalam sabda Rasulullah shallallahu ‘alaihi wa sallam, “Sungguh seorang hamba benar-benar melaksanakan shalat, tapi tidak dituliskan baginya dari (pahala kebaikan) shalat tersebut kecuali sepersepuluhnya, sepersembilannya, seperdelapannya, sepertujuhnya, seperenamnya, seperlimanya, seperempatnya, sepertiganya, atau seperduanya”[10]. '
          '\nJuga dalam hadits lain tentang puasa, Rasulullah shallallahu ‘alaihi wa sallam bersabda, “Terkadang orang yang berpuasa tidak mendapatkan bagian dari puasanya kecuali lapar dan dahaga saja”[11]'),
  ArtikelIslami(
      title: 'Mengadu kepada Allah, bukan kepada Makhluk',
      author: 'dr.Raehanul Bahraeni, M.Sc, Sp.PK',
      date: '25 Agutus 2021',
      image:
          'https://static.muslim.or.id/wp-content/uploads/2021/02/20210214-Mengadu-Kepada-Allah-Bukan-Kepada-Makhluk-810x500.png',
      description:
          ' Salah satu pelajaran tauhid yang luar biasa adalah mengajarkan kita agar tidak mudah mengeluh atau curhat kepada manusia. Mengeluh dan curhat itu hanya kepada Allah Ta’ala. Sedangkan kepada manusia, itu lebih ke arah musyawarah dan diskusi mengenai masalah kita untuk mencari jalan keluar terbaik. Itu pun tidak semua manusia bisa diajak musyawarah dan diskusi, melainkan manusia yang berilmu serta mau membantu kita. '
          '\nSalah satu contoh mengadu kepada Allah Ta’ala adalah sebagaimana yang dilakukan oleh Nabi Ya’qub ‘alaihis salaam. Beliau berkata dan tertulis dalam Al-Qur’an, إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ '
          '\n“Sesungguhnya hanyalah kepada Allah aku mengadukan kesusahan dan kesedihanku” (QS. Yusuf: 86). Ibnul Jauzi Rahimahullah menjelaskan bahwa mengeluh kepada makhluk adalah suatu hal yang dibenci. Beliau rahimahullah berkata, وقد كان السَّلَفُ يكرهون الشَّكوَى إِلَى الخَلقِ. وَالشَّكوَى وَإِن كان فيها رَاحَةٌ إِلا أَنَّـهَا تَدُلُّ عَلَىٰ ضَـعـفٍ وَذُلٍّ. وَالصَّبرُ عنها دَلِيلٌ عَلَى قُـوَّةٍ وَعِزٍّ. '
          '“Para salaf membenci mengeluh kepada makhluk, meski ketika mengeluh tersebut mendatangkan ketenangan. Hal tersebut menunjukkan lemahnya iman dan kerendahan. Bersabar atas musibah menunjukkan kuatnya iman dan kemuliaan seseorang” (Ats-Tsabaat ‘Inda Al-Mamat, hal. 55). '
          'Mengapa dibenci? Karena mengeluh kepada makhluk seolah-olah menunjukkan seorang hamba “mengeluhkan perbuatan (takdir) Rabb-nya kepada sesama makhluk”. Jelas semua yang terjadi adalah perbuatan dan takdir Alah Ta’ala. Kita harus rida dengan semua takdir Allah Ta’ala. '
          'Baca Juga: Sering Menangis Karena Film Sedih, Namun Tidak Pernah Menangis Karena Allah. '
          'Rasulullah Shallallahu ‘alaihi wa sallam bersabda, فَمَنْ رَضِيَ فَلَهُ الرِّضَا، وَمَنْ سَخِطَ فَلَهُ السُّخْطُ '
          '“Barangsiapa yang ridha (menerimanya), maka Allah akan meridhainya. Dan barangsiapa yang murka (menerimanya), maka Allah murka kepadanya” (HR. Tirmidzi). '
          'Hal ini pun dicontohkan oleh Nabi Shallallahu ‘alaihi wa sallam. Ketika ada masalah berat, beliau mengadukan kepada Allah Ta’ala dengan mendirikan shalat.'
          'Sahabat Hudzaifah Radhiallahu ‘anhu berkata, كَانَ النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ إِذَا حَزَبَهُ أَمْرٌ صَلَّى '
          '“Apabila ada masalah berat, Nabi Shallallahu ‘alaihi wa sallam mengerjakan salat” (HR. Ahmad, lihat Shahih Sunan Abi Dawud). '
          'Orang yang segera kembali kepada Allah ketika ada masalah berat, maka hatinya akan kembali tenang. Sebagaimana firman Allah Ta’ala,  الَّذِينَ ءَامَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللهِ أَلاَبِذِكْرِ اللهِ تَطْمَئِنُّ الْقُلُوبُ'
          '“(Yaitu) orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah. Ingatlah, hanya dengan mengingat Allah-lah hati menjadi tenteram” (QS. ar-Rad: 27-28).'
          'Tidak hanya masalah berat saja baru kita mengadu kepada Allah Ta’ala. Akan tetapi, apa pun masalahnya kita meminta kepada Allah Ta’ala dan memohon kepada Allah Ta’ala. Hal ini menunjukkan kesempurnaan tauhid seorang hamba.'
          'Ibnu Rajab Al-Hambali Rahimahullah menjelaskan hendaknya kita meminta meskipun masalah remeh sekalipun seperti tali sandal yang putus. Beliau rahimahullah berkata, ” وفي الحديث دليل على أن الله يحب أن يسأله العباد جميع مصالح دينهم ودنياهم من الطعام والشراب والكسوة وغير ذلك ، كما يسألونه الهداية والمغفرة ، وفي الحديث : ( ليسأل أحدكم ربه حاجته كلها حتى شسع نعله إذا انقطع ) ، وكان بعض السلف يسأل الله في صلاته كل حوائجه حتى ملح عجينه وعلف شاته ، وفي الإسرائيليات : أن موسى عليه الصلاة والسلام قال : يا رب ! إنه ليعرض لي الحاجة من الدنيا فأستحي أن أسألك . قال : سلني حتى ملح عجينك وعلف حمارك .'
          '“Pada hadits terdapat dalil bahwa Allah mencintai hamba-Nya yang meminta kepada-Nya semua maslahat agama dan dunia, baik berupa makanan, minuman, pakaian, dan lain-lain sebagaimana mereka meminta hidayah dan ampunan. Dalam hadits disebutkan, ‘hendaklah setiap kalian meminta kepada Rabb-nya semua kebutuhan, sampai-sampai ketika tali sandalnya lepas’” (Jami’ Al-‘Ulum wal Hikam, 2: 48).'
          'Apabila ada masalah kita tidak mengadu kepada makhluk, tetapi kita diskusikan dan cari jalan keluarnya.Allah Ta’ala berfirman, وَ شَاوِرْهُمْ في الأَمْرِ'
          '“Maka bermusyawarahlah dengan mereka dalam urusan itu” (QS. Al-Imran: 159).'
          'Tentu tidak semua manusia bisa kita ajak musyawarah dan diskusi, tetapi orang yang berilmu dan berpengalaman dalam hal ini. Allah Ta’ala berfirman,فَاسْأَلُواْ أَهْلَ الذِّكْرِ إِن كُنتُمْ لاَ تَعْلَمُونَ'
          '“Tanyalah kepada ahlinya (orang yang berilmu) jika kamu tidak mengetahui” (QS. An-Nahl: 43).Demikian, semoga bermanfaat.'),
  ArtikelIslami(
    title: 'Tidak Boleh Sembarangan Mengkafirkan Seseorang ',
    author: 'Dr.Andy Octavian Latief, M.Sc',
    date: '12 Maret 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/02/20210213-Tidak-Boleh-Sembarangan-Mengkafirkan-Seseorang-810x500.png',
    description:
        '  Di antara akidah ahlussunnah waljama’ah adalah membedakan antara takfīr muṭlaq dan takfīr mu’ayyan. Pertama: al-Takfīr al-Muṭlaq (التكفير المطلق), yaitu menjatuhkan vonis kekufuran kepada suatu keyakinan, ucapan, atau perbuatan yang merupakan pembatal keislaman, atau menjatuhkan vonis kafir kepada pelakunya secara umum tanpa menunjuk pada orang tertentu.'
        '\nContoh:Menyembah berhala adalah kekufuran,Membenci syariat Allah Ta’ala dan tuntunan Nabi-Nya ṣhallallāhu ‘alaihi wa sallam adalah kekufuran,Barangsiapa yang meyakini bahwa shalat itu tidak wajib atau zina itu tidak haram, maka dia kafir.'
        '\nKedua: al-Takfīr al-Mu’ayyan (التكفير المعين), yaitu menjatuhkan vonis kafir kepada seseorang tertentu karena dia telah melakukan suatu pembatal keislaman.'
        '\nContoh: Si Fulan itu kafir.Takfīr mu’ayyan tidak boleh diarahkan kepada seseorang kecuali jika telah terpenuhi syarat-syarat dan hilang penghalang-penghalang dari pengkafirannya. Oleh karena itu, yang hanya boleh melakukan takfīr mu’ayyan adalah para ulama’ besar atau mufti yang telah mengetahui apakah si Fulan yang melakukan pembatal keislaman tersebut telah terpenuhi syarat atau hilang penghalang dari kekafirannya.'
        '\nAdapun tugas kita sebagai penuntut ilmu adalah mempelajari apa saja yang merupakan pembatal keislaman sehingga kita bisa menghindarinya dan memperingatkan orang lain darinya. Dengan kata lain, tugas kita adalah seputar takfīr muṭlaq, bukan takfīr mu’ayyan.'
        '\nRasulullah ṣhallallāhu ‘alaihi wa sallam telah memperingatkan kita agar tidak sembarangan mengkafirkan seseorang secara mu’ayyan.Dari Ibn ‘Umar radhiyallāhu ‘anhumā, bahwa Nabi ṣhallallāhu ‘alaihi wa sallam bersabda,أيما رجل قال لأخيه يا كافر فقد باء بها أحدهما.'
        '\n“Jika seseorang berkata kepada saudaranya, ‘Wahai kafir,’ maka tuduhan itu akan kembali kepada salah satunya.” (HR. Bukhari no. 6104 dan Muslim no. 60. Bukhari juga meriwayatkan hadis ini dari Abu Hurairah radhiyallāhu ‘anhu no. 6103)'
        '\nPara ulama menjelaskan bahwa yang dimaksud “tuduhan itu akan kembali kepada salah satunya” bukan bermakna si penuding itu telah kafir dengan ucapannya. Akan tetapi, ini termasuk dalam bab memberikan ancaman yang keras kepada orang yang melakukan sebuah dosa yang besar di mata syariat.'
        '\nAdapun jika Fulan tersebut telah tegas kekafirannya dalam dalil secara mu’ayyan, maka wajib bagi kita untuk meyakini kekafirannya. Contoh: Fir’aun, Abu Jahl, Abu Lahb, Abu Thalib, dll. Demikian pula orang-orang yang memang beragama selain Islam, maka wajib bagi kita untuk meyakini kekafiran mereka.',
  ),
  ArtikelIslami(
    title: 'Contoh Syirik Akbar dalam Tauhid Rububiyyah',
    author: 'Dr. Andy Octavian Latief, M.Sc.',
    date: '24 Agustus 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/02/20210210-Contoh-Syirik-Akbar-Dalam-Tauhid-Rububiyah-810x500.png',
    description:
        'Di antara bentuk syirik akbar dalam rububiyyah adalah:Pertama: Tidak meyakini bahwa Allah itu ada, sebagaimana yang dilakukan oleh orang-orang ateis.Allah Subhanahu wa Ta’ala berfirman,وَقَالُوا مَا هِيَ إِلَّا حَيَاتُنَا الدُّنْيَا نَمُوتُ وَنَحْيَا وَمَا يُهْلِكُنَا إِلَّا الدَّهْرُ '
        '\n“Mereka berkata, ‘Kehidupan ini tidak lain hanyalah kehidupan di dunia saja. Kita mati dan kita hidup dan tidak ada yang akan membinasakan kita selain masa’” (QS. al-Jatsiyah: 24).'
        '\nKedua: Meyakini tritunggal atau trinitas, sebagaimana yang dilakukan oleh orang-orang Nasrani, yaitu meyakini bahwa Tuhan itu satu tetapi memiliki tiga pribadi: Tuhan Bapa, Tuhan Putra, dan Roh Kudus. Ketiganya itu sama secara esensi dan kedudukan (Bapa sama dengan Putra, dan keduanya sama dengan Roh Kudus), tetapi sebenarnya berbeda satu sama lain (Bapa adalah yang beranak, Putra adalah yang diperanakkan, dan Roh Kudus adalah yang dihembuskan).'
        '\nAllah Subhanahu wa Ta’ala berfirman,لَّقَدْ كَفَرَ الَّذِينَ قَالُوا إِنَّ اللَّـهَ ثَالِثُ ثَلَاثَةٍ ۘ وَمَا مِنْ إِلَـٰهٍ إِلَّا إِلَـٰهٌ وَاحِدٌ “Sesungguhnya telah kafirlah orang-orang yang berkata, ‘Sungguh Allah itu salah satu dari yang tiga.’ Padahal sekali-kali tidak ada tuhan yang berhak diibadahi selain Tuhan yang Satu” (QS. al-Ma’idah: 73).وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ * لَمْ يَلِدْ وَلَمْ يُولَدْ *  اللَّـهُ الصَّمَدُ *قُلْ هُوَ اللَّـهُ أَحَدٌ * '
        '\n“Katakanlah, ‘Dialah Allah, Yang Maha Esa. Allah adalah ash-Shamad (Dzat yang bergantung kepada-Nya segala sesuatu). Dia tidak beranak dan tidak pula diperanakkan. Dan tidak ada sesuatu apa pun yang setara dengan-Nya’” (QS. al-Ikhlash: 1-4).Ketiga: Meyakini bahwa tuhan itu ada dua, yaitu Ahura Mazda dan Ahriman. Hal ini sebagaimana yang diyakini oleh orang-orang Majusi, di mana kebaikan semuanya berasal dari tuhan kebaikan yaitu Ahura Mazda, sedangkan keburukan semuanya berasal dari tuhan keburukan yaitu Ahriman.'
        '\nKeempat: Meyakini bahwa manusia menciptakan perbuatan mereka sendiri, sebagaimana yang diyakini oleh orang-orang Qadariyyah.Allah Subhanahu wa Ta’ala berfirman, وَاللَّـهُ خَلَقَكُمْ وَمَا تَعْمَلُونَ “Padahal Allah-lah yang menciptakan kamu dan apa yang kamu perbuat” (QS. ash-Shaffat: 96).'
        '\nPara ulama berkata,من قال إن أفعال العباد غير مخلوقة فهو بمنزلة من قال إن السماء والأرض غير مخلوقة “Barangsiapa yang berkata, ‘Perbuatan manusia itu tidak diciptakan,’ maka dia sama derajatnya dengan orang yang berkata, ‘Langit dan bumi itu tidak diciptakan.’”'
        'Kelima: Meyakini bahwa syaikh mereka telah mencapai derajat bisa mengatur seluruh apa yang ada di alam semesta ini dengan kalimat “Kun” (“Jadilah!”), baik ketika mereka masih hidup maupun setelah matinya, sebagaimana ini adalah yang diyakini oleh orang-orang Sufi. Allah Subhanahu wa Ta’ala berfirman, إِنَّمَا أَمْرُهُ إِذَا أَرَادَ شَيْئًا أَن يَقُولَ لَهُ كُن فَيَكُونُ“Sesungguhnya keadaan-Nya apabila Dia menghendaki sesuatu maka Dia berkata, ‘Jadilah!’ maka terjadilah” (QS. Yasin: 82).'
        'Keenam: Meyakini bahwa yang menurunkan hujan itu adalah bintang-bintang, bukan Allah Subhanahu wa Ta’ala. Ini sebagaimana yang diyakini oleh kaum musyrikin jahiliyyah.Dari Abu Malik al-Asy’ariy Radhiyallahu ‘anhu bahwa Nabi Shallallahu ‘alaihi wa sallam bersabda,  أربع في أمتي من أمر الجاهلية لا يتركونهن: الفخر في الأحساب، والطعن في الأنساب، والاستسقاء بالنجوم، والنياحة '
        '“Empat perkara dalam umatku yang termasuk perkara jahiliyyah yang tidak mereka tinggalkan: berbangga diri dengan keturunan, mencela nasab, menisbatkan turunnya hujan kepada bintang-bintang, dan meratapi orang yang meninggal dunia” (HR. Muslim no. 934).Demikian pula, menisbatkan hal-hal lainnya seperti masalah rezeki, untung-rugi, jodoh, sehat-sakit, dan sebagainya kepada bintang-bintang, juga adalah kesyirikan.Referensi utama: Syarh Tashil al-’Aqidah al-Islamiyyah, karya Syaikh ‘Abdullah ibn ‘Abdil-’Aziz al-Jibrin.',
  ),
  ArtikelIslami(
    title: 'Untaian Hikmah Imam Hasan al-Bashri',
    author: 'Ari Wahyudi, S.Si.',
    date: '24 Desember 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/02/20210207-Untaian-Hikmah-Imam-Hasan-al-Bashri-810x500.png',
    description:
        'Hasan al-Bashri adalah diantara pembesar ulama tabi’in menengah. Beliau wafat pada tahun 110 H dalam usia 88 tahun, sebagaimana disebutkan oleh Imam Ibnu Abdil Hadi Rahimahullāh (lihat Thabaqāt ‘Ulamā’ al-Hadits, Juz 1 hal. 140-142). Abu Burdah berkata, “Tidaklah aku melihat orang yang lebih mirip dengan para sahabat Muhammad Shallallāhu ‘alaihi wa sallam melebihi dirinya.” (lihat Min A’lām al-Salaf, Juz 1 hal. 143), Abu Ja’far Muhammad bin ‘Ali mengatakan, “Dia itulah -Hasan al-Bashri- orang yang ucapan-ucapannya mirip ucapan para nabi” (lihat Min A’lām al-Salaf, Juz 1 hal. 144).Guru dan murid beliau'
        'Berikut ini sebagian guru-guru Hasan al-Bashri: ‘Imran bin Hushain, al-Mughirah bin Syu’bah, Abu Bakrah, an-Nu’man bin Basyir, Ibnu ‘Abbas, Ibnu ‘Umar, Abdullah bin ‘Amr, Abu Hurairah, Anas bin Malik, dsb. (lihat Min A’lām al-Salaf, Juz 1 hal. 150).'
        'Berikut ini sebagian murid-murid beliau: Humaid ath-Thawil, Ayyub as-Sakhtiyani, Qotadah, Bakr bin Abdullah al-Muzani, Sa’ad bin Ibrahim, Ibnu ‘Aun, al-Mu’alla bin Ziyad, Yunus bin ‘Ubaid, dsb (lihat Min A’lām al-Salaf, Juz 1 hal. 150).Sebagian nasihat dan mutiara hikmah beliau'
        'Hasan al-Bashri rahimahullāh berkata, “Benar-benar ada dahulu seorang lelaki yang memilih waktu tertentu untuk menyendiri, menunaikan sholat dan menasehati keluarganya pada waktu itu, lalu dia berpesan: Jika ada orang yang mencariku, katakanlah kepadanya bahwa ‘dia sedang ada keperluan’.” (lihat al-Ikhlās wa al-Niyyah, hal.65)'
        'al-Hasan rahimahullāh mengatakan, “Kalau bukan karena keberadaan para ulama niscaya keadaan umat manusia tidak ada bedanya dengan binatang.” (lihat Mukhtashar Minhāj al-Qāshidīn, hal. 15)'
        'Hasan al-Bashri rahimahullāh mengatakan, “Demi Allah! Tidaklah tegak urusan agama ini kecuali dengan adanya pemerintah, walaupun mereka berbuat aniaya dan bertindak zalim. Demi Allah! Apa-apa yang Allah perbaiki dengan keberadaan mereka jauh lebih banyak daripada apa-apa yang mereka rusak.” (lihat Da’ā’im Minhāj Nubuwwah, hal. 279)'
        'Hasan al-Bashri rahimahullāh berkata, “Sungguh, apabila aku dijatuhkan dari langit ke permukaan bumi ini lebih aku sukai daripada mengatakan: Segala urusan berada di tanganku!” (lihat Aqwāl Tābi’in fi Masā’il al-Tauhīd wa al-Īmān [1/134])'
        'Hasan al-Bashri rahimahullāh berkata, “Barangsiapa mendustakan takdir sesungguhnya dia telah mendustakan al-Qur’an.” (lihat Aqwāl Tābi’in fi Masā’il al-Tauhīd wa al-Īmān [1/138])'
        'Dikatakan kepada al-Hasan, “Wahai Abu Sa’id, apa yang harus kami lakukan? Kami berteman dengan orang-orang yang selalu menakut-nakuti kami sampai-sampai hati kami terbang melayang.” Maka beliau menjawab, “Demi Allah, sesungguhnya jika kamu bergaul dengan orang-orang yang selalu menakut-nakuti kamu sampai akhirnya kamu benar-benar merasakan keamanan; lebih baik daripada berteman dengan orang-orang yang selalu membuatmu merasa aman sampai akhirnya justru menyeretmu ke dalam keadaan yang menakutkan.” (lihat Aina Nahnu min Hā’ulā’i, hal. 16)'
        'Ada yang berkata kepada al-Hasan, “Sebagian orang mengatakan: Barangsiapa mengucapkan lā ilāha illallāh maka dia pasti masuk surga.”? Maka al-Hasan menjawab, “Barangsiapa yang mengucapkan lā ilāha illallāh kemudian dia menunaikan konsekuensi dan kewajiban darinya maka dia pasti masuk surga.” (lihat Kitāb al-Tauhīd; Risālah Kalimāt al-Ikhlās wa Tahqīq Ma’nāhā oleh Imam Ibnu Rajab rahimahullāh, hal. 40)'
        'al-Hasan rahimahullāh mengatakan, “Salah satu tanda bahwa Allah mulai berpaling dari seorang hamba adalah tatkala dijadikan dia tersibukkan dalam hal-hal yang tidak penting bagi dirinya.” (lihat al-Risalah al-Mugniyyah, hal. 62).'
        'Hasan al-Bashri rahimahullāh berkata, “Sesungguhnya bisa jadi ada seorang yang senantiasa berjihad walaupun tidak pernah menyabetkan pedang -di medan perang- suatu hari pun.” (lihat Tafsīr al-Qur’ān al-‘Azhīm [6/264] cet. Dār Thaibah)'
        'al-Hasan rahimahullāh menangis sejadi-jadinya, maka ditanyakan kepadanya, “Wahai Abu Sa’id, apa yang membuatmu menangis?”. Maka beliau menjawab, “Karena takut kalau Allah melemparkan aku ke dalam neraka dan tidak memperdulikan nasibku lagi.” (lihat Aina Nahnu min Hā’ulā’i, hal. 75)'
        'Hasan al-Bashri rahimahullāh berkata, “Wahai anak Adam. Sesungguhnya engkau adalah kumpulan perjalanan hari. Setiap hari berlalu maka hilanglah sebagian dari dirimu.” (lihat Ma’ālim fi Tharīq Thalab al-‘Ilmi, hal. 35)'
        'Demikianlah sekelumit faidah yang bisa kami sajikan dengan taufik dari Allah semata. Semoga bisa memberikan manfaat dan pencerahan bagi kita. Wa shallallāhu ‘alā Nabiyyinā Muhammadin wa ‘alā ālihi wa sallam. Walhamdulillāhi Rabbil ‘ālamīn.',
  ),
  ArtikelIslami(
    title: 'Perbedaan Antar Madzhab',
    author: 'Fauzan Hidayat',
    date: '11 Jnauari 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/02/20210206-Perbedaan-Antar-Madzhab-1-810x500.png',
    description:
        'Fatwa Syaikh Abdul Aziz bin Baaz Rahimahullah \nPertanyaan: Apakah perbedaan antar mazhab yang empat? Adakah mazhab yang lebih baik dari yang lain?'
        'Jawaban: Semua mazhab yang empat menginginkan kebenaran. Mazhab Syafi’i, Maliki, Hanbali, dan Hanafi Rahimahumullah semuanya bertujuan mengikuti kebenaran sesuai petunjuk Alquran dan sunah Rasulullah Shallahu ‘alaihi wa sallam. Akan tetapi, sikap ta’ashub (fanatik terhadap mazhab tertentu -pent.) merupakan perbuatan yang tercela.'
        'Adapun mazhab lain yang masyhur dikenal selain 4 mazhab ini adalah mazhab az-Dzahiri. Begitu pula dikenal mazhab yang lain seperti al-Jaririyyah, al-Laitsiyyah, al-Sauriyah (yang merupakan pengikut Sufyan at-Tsauri dan pengikut al-Laits ibn Jarir), juga mazhab ar-Rahawiyyah (namun saat ini tidak ada lagi) yang merupakan pengikut Ishaq bin Rahawiyyah.'
        'Bagaimanapun, yang terpenting dalam bermazhab adalah mengikuti kebenaran. Mazhab yang empat, mazhab az-Zahiriyyah serta mazhab-mazhab sebelumnya (yang tidak lagi menjadi rujukan); semuanya bertujuan untuk mengikuti kebenaran. Kadangkala masing-masing mazhab berbeda pendapat tentang suatu perkara agama. Perbedaan yang alot namun sarat hikmah tersebut disebabkan karena semuanya merujuk pada dalil Alquran dan Assunah sehingga pada akhirnya mazhab-mazhab ini dikenal oleh umat di dunia. Bertambahlah pengikut masing-masing mazhab tersebut yang kemudian populer dalam beberapa perkara agama.'
        'Pendapat satu mazhab terkadang berbeda pandangan dengan pendapat mazhab lainnya sebab kadangkala suatu dalil ada yang jelas bagi satu mazhab (maknanya -pent.), tetapi tersembunyi bagi mazhab lainnya.'
        'Adapun perkara yang diperselisihkan merupakan perkara cabang (furu’) dan tidak ada perbedaan dalam permasalahan pokok (landasan agama atau ushul). Akan tetapi, sikap ta’ashub terhadap suatu pendapat mazhab yang tertentu tanpa keyakinan akan kebenaran yang terkandung di dalamnya merupakan perbuatan yang tercela. Karena telah umum diketahui bahwa semua mazhab bertujuan mengikuti  kebenaran yang berpedoman pada petunjuk Alqur’n dan Assunah serta konsisten di bawah manhaj yang diajarkan oleh Rasulullah Shallallahu ‘alaihi wa sallam.',
  ),
  ArtikelIslami(
    title: 'Menyebut Non Muslim sebagai Saudara',
    author: 'Muhammad Fadli, ST.',
    date: '23 September 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/02/20210204-Menyebut-Non-Muslim-sebagai-Saudara-810x500.png',
    description:
        'Fatwa Syekh Abdul Aziz bin Baz Rahimahullah Ta’ala. Pertanyaan: Seorang teman yang beragama Kristen tinggal bersamaku dan dia memanggilku dengan sebutan “saudaraku” dan dia juga mengatakan “kita adalah saudara”. Dia makan dan minum bersama kami. Apakah hal ini dibolehkan ataukah tidak?'
        '\nJawaban:Seorang muslim bukanlah saudara bagi orang kafir. Allah Subhanahu wa ta’ala berfirman,إِنَّمَا ٱلْمُؤْمِنُونَ إِخْوَةٌ  “Sesungguhnya orang-orang beriman itu bersaudara” (QS. Al-Hujurat [49]: 10). Nabi Shallallahu ‘alaihi wa sallam bersabda,اَلْمُسْلِمُ أَخُو الْمُسْلِمُ'
        '“Seorang Muslim adalah saudara bagi Muslim lainnya” (HR. Al-Bukhari [2: 98], Abu Dawud [4893], At-Tirmidzi [1: 268], Ahmad [2: 91], dari ‘Abdullah bin ‘Umar Radhiyallahu ‘anhu). Maka seorang kafir, baik itu Yahudi, Nasrani, penganut paganisme (penyembah berhala), Majusi, Komunis, atau yang lainnya, bukanlah saudara bagi seorang Muslim. Tidak boleh menjadikan mereka sebagai sahabat dekat atau teman dekat. Adapun sekedar makan bersamanya di beberapa kesempatan insidental, tanpa menjadikannya seorang sahabat dekat atau teman dekat, hanya seperti pada jamuan umum atau sama-sama hadir di acara makan-makan, maka hal itu tidak mengapa.'
        'Adapun menjadikan mereka sebagai sahabat dekat, teman duduk, dan teman makan, maka ini tidak boleh. Karena Allah Ta’ala telah memutus muwalah (loyalitas) dan rasa cinta antara kaum Muslimin dan kaum kafir. Allah Subhanahu wa ta’ala berfirman dalam Al-Qur’an Al-‘Azhim, قَدْ كَانَتْ لَكُمْ أُسْوَةٌ حَسَنَةٌ فِي إِبْرَاهِيمَ وَالَّذِينَ مَعَهُ إِذْ قَالُوا لِقَوْمِهِمْ إِنَّا بُرَآءُ مِنْكُمْ وَمِمَّا تَعْبُدُونَ مِنْ دُونِ اللَّهِ كَفَرْنَا بِكُمْ وَبَدَا بَيْنَنَا وَبَيْنَكُمُ الْعَدَاوَةُ وَالْبَغْضَاءُ أَبَدًا حَتَّى تُؤْمِنُوا بِاللَّهِ وَحْدَهُ “Sungguh telah ada bagi kalian uswah hasanah (suri tauladan yang baik) di dalam diri Ibrahim dan orang-orang yang bersamanya, ketika mereka berkata kepada kaum mereka, ‘Sesungguhnya kami berlepas diri dari kalian dan dari semua yang kalian sembah selain dari Allah.'
        'Kami kufur (ingkari) terhadap (kekufuran) kalian dan telah nyata antara kami dan kalian permusuhan dan kebencian untuk selama-lamanya sampai kalian beriman kepada Allah semata’” (QS. Al-Mumtahanah [60]: 4). Allah Subhanahu wa ta’ala juga berfirman, لا تَجِدُ قَوْمًا يُؤْمِنُونَ بِاللَّهِ وَالْيَوْمِ الْآخِلَّا تَجِدُ قَوْمًا يُؤْمِنُونَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ يُوَآدُّونَ مَنْ حَآدَّ ٱللَّهَ وَرَسُولَهُۥ وَلَوْ كَانُوٓا۟ ءَابَآءَهُمْ أَوْ أَبْنَآءَهُمْ أَوْ إِخْوَٰنَهُمْ أَوْ عَشِيرَتَهُمْ ۚ“Kamu tidak akan jumpai sebuah kaum yang mereka beriman kepada Allah dan hari akhirat, saling berkasih sayang dengan orang-orang yang menentang Allah dan Rasul-Nya. Walaupun orang-orang itu adalah bapak-bapak mereka, anak-anak mereka, saudara-saudara mereka, ataupun keluarga mereka” (QS. Al-Mujadilah [58]: 22).'
        'Wajib bagi seorang muslim berlepas diri dari pelaku kesyirikan dan membenci mereka, karena Allah Ta’ala. Tetapi tidak boleh menyakiti, membahayakan, dan menyerang mereka tanpa hak (tanpa alasan yang bisa dibenarkan), jika mereka tidak melakukan permusuhan kepada kita (kafir harbi). Di sisi lain juga, jangan menjadikan mereka sahabat dekat atau saudara. Ketika berpapasan dan makan bersama mereka di jamuan umum atau sama-sama hadir di acara makan-makan tanpa rasa persahabatan, loyalitas, dan kasih sayang (dengan mereka), maka hal itu tidak mengapa.'
        'Seorang Muslim dalam bermuamalah dengan orang kafir, selama mereka tidak memusuhi kaum muslimin, wajib bermuamalah dengan muamalah Islami. Maksudnya dengan menjalankan amanah, tidak berbuat kecurangan, tidak berkhianat, dan tidak berdusta. Apabila terdapat perdebatan antara Muslim dan kafir, maka debatlah dengan cara yang baik. Bersikap adillah kepada mereka dalam perselisihan tersebut. Hal ini dalam rangka mengamalkan firman Allah Ta’ala, وَلا تُجَادِلُوا أَهْلَ الْكِتَابِ إِلا بِالَّتِي هِيَ أَحْسَنُ إِلا الَّذِينَ ظَلَمُوا مِنْهُمْ “Dan janganlah kalian berdebat dengan ahlul kitab melainkan dengan cara yang paling baik, kecuali dengan orang-orang yang berbuat zalim dari mereka” (QS. Al-‘Ankabut [29]: 46).'
        'Seorang muslim disyariatkan untuk mendakwahi mereka kepada kebaikan dan menasihati mereka, serta bersabar dalam melakukan hal tersebut. Juga disertai sikap yang baik dalam bertetangga dan senantiasa mengatakan perkataan yang baik. Hal ini berdasarkan firman Allah ‘Azza Wa Jalla,ادْعُ إِلَى سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ وَجَادِلْهُمْ بِالَّتِي هِيَ أَحْسَنُ “Serulah (manusia) kepada jalan Rabbmu dengan hikmah dan mau’izhah al-hasanah (pelajaran yang baik) dan bantahlah mereka dengan cara yang baik” (QS. An-Nahl [16]: 125).Allah Subhanahu wa ta’ala juga berfirman, وَقُولُوا لِلنَّاسِ حُسْنًا “Dan katakanlah kepada manusia yang baik” (QS Al-Baqarah [2]: 183).'
        'Nabi Shallallahu ‘alaihi wa sallam bersabda,مَنْ دَلَّ عَلَى خَيْرٍ فَلَهُ مِثْلُ أَجْرَ فَاعِلِهِ “Barangsiapa yang menunjukkan kepada kebaikan, maka baginya pahala sebesar dengan pahala pelakunya” (HR. Ahmad [5: 274], Ibnu Hibban no. 867 dan 868. Disahihkan oleh Al-Albani dalam Silsilah Al-Ahadits Ash-Shahihah no. 1660).Ayat-ayat dan hadis-hadis semakna dengan ini banyak sekali',
  ),
  ArtikelIslami(
    title: 'Nasihat Bagi yang Terjerumus dalam Kesyirikan',
    author: 'Fauzan Hidayat',
    date: '4 Oktober 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/01/20210131-Nasihat-Bagi-Yang-Terjerumus-dalam-Kesyirikan-810x500.png',
    description:
        'Fatwa Syaikh Muhammad Ali Farkus \nPertanyaan:Banyak dari ikhwan kita yang menghadapi permasalahan dengan ayah atau ibu, paman atau bibi, dan orang-orang terdekat mereka yang terjerumus ke dalam praktek kesyirikan dengan melakukan ritual-ritual ibadah kepada selain Allah, seperti berdoa, ber-istighotsah, bertawakal bahkan sampai mencela Allah Ta’ala dan agama-Nya. Sementara sebagian besar mereka menolak untuk dinasihati. Mohon nasihatnya atas cobaan yang berat yang menimpa saudara kita dan keluarganya ini. Jazakallah khairan. Jawaban:'
        'Alhamdulillah, segala puji bagi Allah, Rabb Semesta Alam. Selawat dan salam semoga senantiasa tercurahkan atas utusan Allah -Nabi Muhammad Shallallahu ‘alaihi wa sallam– rahmat bagi semesta alam. Juga atas para sahabat dan keluarganya hingga hari akhir.Allah Ta’ala murka kepada pelaku kesyirikan dan Allah perintahkan kepada hamba-Nya untuk berlepas diri dari mereka serta tiada hak bagi mereka untuk mendapatkan mahabbah (rasa cinta) dan kesetiaan. Sebab akidah al-wala’ wal bara’ merupakan pondasi iman yang paling pokok bagi seorang muslim dan menjadi syarat kesempurnaan syahadat yang menyatukan hati muslimin. '
        'Sebagaimana firman Allah Ta’ala,لَا تَجِدُ قَوْمًا يُؤْمِنُونَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ يُوَادُّونَ مَنْ حَادَّ اللَّهَ وَرَسُولَهُ وَلَوْ كَانُوا آبَاءَهُمْ أَوْ أَبْنَاءَهُمْ أَوْ إِخْوَانَهُمْ أَوْ عَشِيرَتَهُمْ ۚ “Kamu tidak akan mendapati kaum yang beriman kepada Allah dan hari akhirat, saling berkasih-sayang dengan orang-orang yang menentang Allah dan Rasul-Nya, sekalipun orang-orang itu adalah bapak-bapak, atau anak-anak, atau saudara-saudara ataupun keluarga mereka” (QS. al-Mujadilah: 22).Rasulullah Shallallahu ‘alaihi wasallam bersabda,لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى أَكُونَ أَحَبَّ إِلَيْهِ مِنْ وَالِدِهِ وَوَلَدِهِ وَالنَّاسِ أَجْمَعِينَ “Tidaklah (sempurna) iman salah seorang di antara kalian sehingga aku lebih dicintainya daripada orangtuanya, '
        'anaknya dan segenap umat manusia ”[1]. Allah Ta’ala juga telah memerintahkan Rasul-Nya untuk berlepas diri dari perbuatan keluarga atau saudara yang menentang perintah Allah Ta’ala. Sebagaimana firman-Nya, (وَأَنذِرۡ عَشِيرَتَكَ ٱلۡأَقۡرَبِينَ (٢١٤) وَٱخۡفِضۡ جَنَاحَكَ لِمَنِ ٱتَّبَعَكَ مِنَ ٱلۡمُؤۡمِنِينَ (٢١٥) فَإِنۡ عَصَوۡكَ فَقُلۡ إِنِّي بَرِيٓءٞ مِّمَّا تَعۡمَلُونَ(٢١٦ “Dan berilah peringatan kepada kerabat-kerabatmu (Muhammad) yang terdekat, dan rendahkanlah dirimu terhadap orang-orang yang beriman yang mengikutimu. Kemudian jika mereka mendurhakaimu, maka katakanlah (Muhammad), ‘Sesungguhnya aku tidak bertanggung jawab (berlepas diri) terhadap apa yang kamu kerjakan’” (QS. as-Syu’ara: 214-216).Akan tetapi, berlepas diri dari perbuatan buruk mereka tidak berarti bermaksud menyinggung perasaan mereka,baik dengan perkataan maupun perbuatan. Justru mengajak dan mendakwahkan mereka agar kembali ke jalan Allah merupakan kewajiban seorang muslim terhadap kerabat terdekatnya '
        '(ayah, ibu, saudara, dan seterusnya) sebagaimana firman Allah,فَذَكِّرۡ إِن نَّفَعَتِ ٱلذِّكۡرَىٰ “Maka berikanlah peringatan, karena peringatan itu bermanfaat” (QS. Al-A’la: 9). Hendaklah dia berbuat baik kepada orang tuanya, meskipun keduanya berbuat kesyirikan. Tidak boleh meninggalkan mereka, bahkan dia harus memperlakukan mereka dengan baik. Sebagaimana Allah perintahkan hal ini dalam Alquran, : وَإِن جَٰهَدَاكَ عَلَىٰٓ أَن تُشۡرِكَ بِي مَا لَيۡسَ لَكَ بِهِۦ عِلۡمٞ فَلَا تُطِعۡهُمَاۖ وَصَاحِبۡهُمَا فِي ٱلدُّنۡيَا مَعۡرُوفٗاعليه﴿ الآيةُ في قوله تعالى “Dan jika keduanya memaksamu untuk mempersekutukan dengan Aku, sesuatu yang tidak ada pengetahuanmu tentang itu, maka janganlah kamu mengikuti keduanya, dan pergaulilah keduanya di dunia dengan baik, dan ikutilah jalan orang yang kembali kepada-Ku. Kemudian hanya kepada-Kulah kembalimu, maka Ku-beritakan kepadamu apa yang telah kamu kerjakan” (QS. Luqman: 15).'
        'Hukum terhadap kerabat sama dengan hukum terhadap kedua orang tua. Mereka memiliki hak untuk menyambung persaudaraan, nafkah, dan mendapatkan perilaku yang baik. Sebagaimana keumuman  firman Allah Ta’ala, وَٱعۡبُدُواْ ٱللَّهَ وَلَا تُشۡرِكُواْ بِهِۦ شَيۡ‍ٔٗاۖ وَبِٱلۡوَٰلِدَيۡنِ إِحۡسَٰنٗا وَبِذِي ٱلۡقُرۡبَىٰ وَٱلۡيَتَٰمَىٰ وَٱلۡمَسَٰكِينِ وَٱلۡجَارِ ذِي ٱلۡقُرۡبَىٰ وَٱلۡجَارِ ٱلۡجُنُبِ وَٱلصَّاحِبِ بِٱلۡجَنۢبِ وَٱبۡنِ ٱلسَّبِيلِ وَمَا مَلَكَتۡ أَيۡمَٰنُكُمۡ“Sembahlah Allah dan janganlah kamu mempersekutukan-Nya dengan sesuatupun. Dan berbuat baiklah kepada dua orang ibu-bapak, karib-kerabat, anak-anak yatim, orang-orang miskin, tetangga yang dekat dan tetangga yang jauh, dan teman sejawat, ibnu sabil dan hamba sahayamu. Sesungguhnya Allah tidak menyukai orang-orang yang sombong dan membangga-banggakan diri” (QS. an-Nisa’: 36).Namun demikian, kebaikan bagi mereka bukan berarti mendukung kekufuran dan penentangan mereka terhadap agama Islam. Sebab perbuatan tersebut terlarang dalam syariat. '
        'Allah Ta’ala telah membatasi perilaku kita terhadap mereka dengan firman-Nya,وَمَن يَتَوَلَّهُم مِّنكُمۡ فَإِنَّهُۥ مِنۡهُمۡۗ “Barangsiapa di antara kamu yang menjadikan mereka teman setia [wali, pelindung atau pemimpin], maka sesungguhnya dia termasuk golongan mereka” (QS. Al-Ma’idah: 51).Dalam hal mendakwahi mereka hendaklah dilakukan dengan cara yang telah diajarkan dalam agama (yaitu lemah lembut dan penuh hikmah -pent.), tanpa menggunakan cara-cara yang kasar sebagaimana firman Allah Ta’ala, ادْعُ إِلَىٰ سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ ۖ وَجَادِلْهُمْ بِالَّتِي هِيَ أَحْسَنُ ۚ إِنَّ رَبَّكَ هُوَ أَعْلَمُ بِمَنْ ضَلَّ عَنْ سَبِيلِهِ ۖ وَهُوَ أَعْلَمُ بِالْمُهْتَدِينَ“Serulah (manusia) kepada jalan Tuhan-mu dengan hikmah dan pelajaran yang baik dan bantahlah mereka dengan cara yang baik. Sesungguhnya Tuhanmu Dialah yang lebih mengetahui tentang siapa yang tersesat dari jalan-Nya dan Dialah yang lebih mengetahui orang-orang yang mendapat petunjuk” (QS. an-Nahl: 125).'
        'Karena dengan cara ini (sebagaimana yang diajarkan dalam Al-Qur’an -pent.) merupakan metode yang paling penting dalam dakwah dan sangat bermanfaat serta membekas di hati manusia. Rasulullah Shallahahu ‘alaihi wa sallam telah bersabda mengenai hal ini, نْ يَهْدِيَ اللَّهُ بِكَ رَجُلًا وَاحِدًا خَيْرٌ لَكَ مِنْ أَنْ يَكُونَ لَكَ حُمْرُ النَّعَمِ“Sungguh seandainya Allah memberi hidayah kepada seseorang lewat perantaraan kamu, hal itu lebih baik buatmu dari pada unta merah (harta yang paling baik)” [2].Pengetahuan (ilmu) hanya milik Allah Ta’ala, dan akhir kalam walhamdulillah Rabbil ‘alamin, wa shalllahu ‘ala Nabi Muhammad wa ‘ala ashhabihi wa ikhwanihi ila yaumiddin, wa sallim tasliman.',
  ),
  ArtikelIslami(
    title: 'Ibnu Taimiyah dan Lisan Beliau yang Terjaga',
    author: 'Muhammad Nur Ichwan Muslim, ST.',
    date: '17 Agustus 2021',
    image:
        'https://static.muslim.or.id/wp-content/uploads/2021/01/20210122-Ibnu-Taimiyah-dan-Lisan-Beliau-yang-Terjaga-810x500.png',
    description:
        'Meski banyak orang, baik dari kalangan alim, qadhi, dan amir, yang memusuhi dan memprovokasi agar masyarakat membenci beliau, Syaikhul Islam Ibnu Taimiyah Rahimahullah berusaha menahan lisan beliau untuk tidak mencela kehormatan mereka dan hanya membalas jika mereka adalah ahli bidah yang menyeru kepada bidah yang mereka lakukan.Oleh karena itu, dalam karya beliau tidak ditemukan umpatan kepada seorang pun kecuali ada alasan tepat yang menuntut hal itu. Misalnya, orang tersebut membuat kedustaan atas diri beliau atau agama. Dalam hal itu, beliau pasti akan melakukan bantahan dan menjelaskan kesalahannya. Di saat yang sama, ulama yang berseberangan pendapat dengan beliau, terkadang begitu gampang menggunakan lisan mereka untuk mencela kehormatan, menuduh niat, dan menyalahkan akidah beliau, bahkan sampai pada taraf mengkafirkan dan menghalalkan darah Syaikhul Islam Ibnu Taimiyah Rahimahullah.'
        'Ibnu al-Qayyim Rahimahullah pernah mengatakan,  إني لكم مكانه ولا يكون لكم أمر تحتاجون فيه إلى مساعدة إلا وساعدتكم فيه ونحو هذا من الكلام فسروا به ودعوا له وعظموا هذه الحال منه وجئت يوما مبشرا له بموت أكبر أعدائه وأشدهم عداوة وأذى له فنهرني وتنكر لي واسترجع ثم قام من فوره إلى بيت أهله فعزاهم وقال : وما رأيته يدعو على أحد منهم قط وكان يدعو لهم. وددت أني لأصحابي مثله لأعدائه وخصومه.وكان بعض أصحابه الأكابر يقول : “Beberapa sahabat senior beliau (Ibnu Taimiyah) kerap berucap, ‘Aku berharap bisa bersikap dengan para sahabatku sebagaimana Ibnu Taimiyyah bersikap dengan musuh-musuhnya.’ Saya sama sekali tidak pernah melihat beliau mendoakan musuh agar tertimpa keburukan, bahkan beliau sering mendoakan agar mereka mendapatkan kebaikan,'
        'Suatu hari, aku menemui beliau untuk menyampaikan kabar gembira berupa meninggalnya musuh terbesar beliau, sekaligus orang yang paling memusuhi dan paling suka menyakiti beliau. Mendengar berita yang kusampaikan, beliau membentakku, menyalahkan sikapku, dan mengucapkan istirja’ (inna lillahi wa inna ilahi raji’un). Kemudian beliau bergegas pergi menuju rumah orang tersebut.'
        'Beliau lantas menghibur keluarga yang ditinggal mati. Bahkan beliau mengatakan, ‘Aku adalah pengganti beliau untuk kalian. Jika kalian memerlukan suatu bantuan, pasti aku akan membantu kalian’; dan ucapan semisal itu. Akhirnya mereka pun bergembira, mendoakan kebaikan untuk Ibnu Taimiyyah, dan sangat kagum dengan sikap Ibnu Taimiyyah tersebut” (Madaarij as-Salikin, 2: 345).Ibnu Taimiyah Rahimahullah adalah pribadi yang kerap memuji dan menyanjung ulama yang hidup sezaman dengan beliau. Beliau menggelari mereka dengan gelar yang sesuai dengan kedudukan mereka.Beliau Rahimahullah menyifati Taqiyuddin Ibnu Daqiq al-‘Ied Rahimahullah dengan sebutan seorang syekh di masa itu (Majmu’ al-Fatawa, 2: 244).Ibnu Taimiyah Rahimahullah menyifati Syekh Jamaluddin al-Maraghi Rahimahullah dengan sosok yang alim, arif, dan syekh di zaman itu (Majmu’ al-Fatawa, 2: 244).'
        'Beliau menyebut Tajuddin al-Anbari Rahimahullah sebagai pakar fikih yang utama (Majmu’ al-Fatawa, 2: 246).Ibnu Taimiyah menyanjung Syekh Imaduddin ‘Abdurrahman ibn Abi ash-Shu’r al-Anshariy Rahimahullah sebagai sosok tokoh dan teladan kami (Majmu’ al-Fatawa, 2: 463, 18: 98).Beliau bahkan memuji dan menyanjung Syekh Nashr al-Manbaji, seorang yang terkenal memusuhi beliau. Ibnu Taimiyah Rahimahullah bahkan pernah menulis surat kepada Syekh Nashr al-Manbaji Rahimahullah, إلَى الشَّيْخِ الْعَارِفِ الْقُدْوَةِ السَّالِكِ النَّاسِكِ أَبِي الْفَتْحِ نَصْرٍ فَتَحَ اللَّهُ عَلَى بَاطِنِهِ وَظَاهِرِهِ مَا فَتَحَ بِهِ عَلَى قُلُوبِ أَوْلِيَائِهِ وَنَصَرَهُ عَلَى شَيَاطِينِ الْإِنْسِ وَالْجِنِّ فِي جَهْرِهِ وَإِخْفَائِهِ وَنَهَجَ بِهِ الطَّرِيقَةَ الْمُحَمَّدِيَّةَ الْمُوَافِقَةَ لِشِرْعَتِهِمِنْ أَحْمَدَ ابْنِ تَيْمِيَّة: “Dari Ahmad Ibnu Taimiyah kepada Syekh, al-Arif (yang bijak), al-Qudwah (teladan), as-Salik (penempuh jalan ruhani), an-Nasik (pegiat ibadah), Abu al-Fath Nashr, semoga Allah membukakan batiniah dan lahiriahnya, agar memperoleh berbagai karunia yang dianugerahkan ke hati para wali-Nya. Semoga Allah menolongnya dari setan yang berwujud manusia dan jin, baik di kala ramai maupun bersendiri. Dan semoga Allah menjadikan dirinya sebagai sosok yang menjelaskan kepada umat jalan beragama yang sesuai dengan ajaran Muhammad.”'
        'Ibnu Taimiyah Rahimahullah melanjutkan, فَإِنَّ اللَّهَ تَعَالَى قَدْ أَنْعَمَ عَلَى الشَّيْخِ وَأَنْعَمَ بِهِ نِعْمَةً بَاطِنَةً وَظَاهِرَةً فِي الدِّينِ وَالدُّنْيَا وَجَعَلَ لَهُ عِنْدَ خَاصَّةِ الْمُسْلِمِينَ – الَّذِينَ لَا يُرِيدُونَ عُلُوًّا فِي الْأَرْضِ وَلَا فَسَادًا – مَنْزِلَةً عَلِيَّةً وَمَوَدَّةً إلَهِيَّةً؛ لِمَا مَنَحَ اللَّهُ تَعَالَى بِهِ مِنْ حُسْنِ الْمَعْرِفَةِ وَالْقَصْدِ “Sesungguhnya Allah Ta’ala tidak hanya menganugerahkan berbagai kenikmatan batin dan lahir kepada Syekh Nashr, tetapi juga menjadikan beliau sosok yang menebarkan kenikmatan batin dan lahir bagi sesama dalam hal agama maupun dunia. Allah Ta’ala menganugerahkan beliau kedudukan yang mulia dan kecintaan yang tulus di hati kaum muslimin yang istimewa, yaitu mereka yang tidak ingin menyombongkan diri dan berbuat kerusakan di muka bumi. Semua itu diperoleh karena makrifah dan niat tulus yang dikaruniakan Allah Ta’ala pada beliau.” '
        'Di akhir surat, Ibnu Taimiyah Rahimahullah mendoakan Syekh Nashr dengan ucapan beliau, وأنا أسأل الله العظيم أن يصلح أمر المسلمين عامتهم وخاصتهم ويهديهم إلى ما يقربهم وأن يجعل الشيخ من دعاة الخير الذين قال الله سبحانه فيهم  : {ولتكن منكم أمة يدعون إلى الخير ويأمرون بالمعروف وينهون عن المنكر وأولئك هم المفلحون}'
        '“Saya memohon kepada Allah, Dzat yang Mahaagung, agar memperbaiki setiap urusan kaum muslimin, baik yang bersifat pribadi maupun umum. Semoga Allah memberikan petunjuk kepada mereka agar mampu mengerjakan segala hal yang bisa mendekatkan hati dan menjadikan Syekh Nashr sebagai sosok penyeru kebaikan seperti yang dimaksud dalam firman Allah Ta’ala, ‘Dan hendaklah di antara kamu ada segolongan orang yang menyeru kepada kebajikan, menyuruh (berbuat) yang makruf, dan mencegah dari yang mungkar. Dan mereka itulah orang-orang yang beruntung’” (Majmu’ al-Fatawa, 2: 452-479).Itulah Syaikhul Islam Ibnu Taimiyah Rahimahullah. Beliau bukanlah sosok yang menyimpan dendam kepada kaum muslimin. Bukan pula sosok yang gemar mencela kaum muslimin, apalagi karena kesalahan mereka dalam berijtihad. Hati beliau tidak memuat kedengkian kepada musuh, bahkan beliau memuji dan menyanjung mereka. Hal menunjukkan keutamaan mereka kepada kaum muslimin dan mengakui keunggulan mereka.Maka, sepatutnya bagi orang yang mengaku mencintai Ibnu Taimiyah untuk berhias dengan sifat dan akhlak beliau.',
  ),
];
